# ========================================
# backend/render.yaml
# Render Blueprint Configuration
# ========================================
services:
  - type: web
    name: acadwell-backend
    runtime: python
    region: singapore  # Change to your preferred region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12
      - key: PORT
        value: 5000
      # Add other environment variables in Render dashboard


