# ========================================
# backend/render.yaml
# Render Blueprint Configuration
# ========================================
services:
  - type: web
    name: acadwell-backend
    runtime: python
    region: singapore  # Change to your preferred region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 0.0.0.0:$PORT --timeout 120 "wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12
      - key: PORT
        value: 5000
      # Add other environment variables in Render dashboard


